### ISSUE TITLE
html5 simplemousegame build broken on safari

### ISSUE THREAD

**Issue by increpare** [haxegon/haxegon-samples#11]
doesn't run on safari for me -

[Error] Error: [lime.app.Preloader] ERROR: Error loading asset "data/sounds/hit.ogg"
	error (simplemousegame.js:33793)
	(anonyme Funktion) (simplemousegame.js:16434)
	error (simplemousegame.js:16554)
	load_onError (simplemousegame.js:32890:146)
	(anonyme Funktion) (simplemousegame.js:32713)
	error (simplemousegame.js:16554)
	(anonyme Funktion) (simplemousegame.js:30127)
	(anonyme Funktion) (howler.min.js:2:16173)
	(anonyme Funktion)

**Comment by increpare** [comment]
(the ogg files seem to be there, so not sure what the problem is)

**Comment by TerryCavanagh** [comment]
Sorry about this - I'll look into it!
