### ISSUE TITLE
02 - Moving Hexagon is not centered appropriately

### ISSUE THREAD

**Issue by TheSpydog** [haxegon/haxegon-samples#12]
When testing the Moving Hexagon sample with Haxegon 0.11, I noticed that the hexagon was drawn in the lower-right of the screen instead of the center. This occurred on both Mac and HTML5 targets.

After playing around a bit, I believe the issue is that `Gfx.screenwidthmid` and `Gfx.screenheightmid` are not correctly defined as of the init() call. Is something missing from the example or is this a bug with the framework?

**Comment by TerryCavanagh** [comment]
This is a bug! Thank you!

The openfl 7.0 release came just a few hours before me, and I think I might have missed something as a result. Gonna investigate, cheers!

**Comment by TerryCavanagh** [comment]
Got it! It's fixed in dev, I'll push the update in a few days in a 0.11.1 version. Thanks!

https://github.com/TerryCavanagh/haxegon/issues/209
