### ISSUE TITLE
Tiny Heist doesn't compile natively as of 0.11.1

### ISSUE THREAD

**Issue by TerryCavanagh** [haxegon/haxegon-samples#13]
Seems to be related to changes in OpenFL/Lime, so it might fix it self. Wait a couple of weeks and try again!

If that doesn't work, maybe try and figure out why it's happening?

```
Error: Localworld.cpp
c:\blah\haxegon\haxegon-samples\complete games\02 - tiny heist\bin\windows\obj\src\gamecontrol\localworld.cpp(1900) : fatal error C1001: An internal error has occurred in the compiler.
(compiler file 'f:\dd\vctools\compiler\utc\src\p2\main.c', line 228)
 To work around this problem, try simplifying or changing the program near the locations listed above.
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information
INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\cl.exe'
    Please choose the Technical Support command on the Visual C++
    Help menu, or open the Technical Support help file for more information

Build halted with errors.
```

**Comment by TerryCavanagh** [comment]
This works again, whoop

**Comment by azrafe7** [comment]
Mmmh... I'm facing this exact same error with the latest (git) haxegon ver and cpp, but only in cpp release mode (not debug). Which could probably suggest some uninitialized memory somewhere (maybe??).

Let me clarify: running `lime test windows` inside the tinyheist dir errors out, at some point, with 
```
C:\azrafe7\haxegon-samples_git\complete games\02 - Tiny Heist>lime test windows
Creating C:/azrafe7/haxegon-samples_git/complete games/02 - Tiny Heist/bin/windows/obj/obj/msvc19-nc
xp/__pch/haxe/hxcpp.pch...
hxcpp.cpp

Compiling group: haxe
cl.exe -Iinclude -nologo /WX- /fp:precise -DHX_WINDOWS -D_USING_V140_SDK71_ -GR -O2(optim-std) -Zi(d
ebug) -FdC:\azrafe7\haxegon-samples_git\complete games\02 - Tiny Heist\bin\windows\obj\obj/msvc19-nc
xp/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -Oy- -c -EHs -GS- -arch:SSE2 -IC:/HaxeToolk
it/haxe/lib/hxcpp/3,4,188/include -DHXCPP_VISIT_ALLOCS(haxe) -DHXCPP_API_LEVEL=331(haxe) -D_CRT_SECU
RE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main)
 -wd4996 ... tags=[haxe,static]
 - src/openfl/system/Capabilities.cpp
 - src/lime/utils/ObjectPool_openfl__internal_TouchData.cpp
 - src/lime/utils/ObjectPool.cpp  [haxe,release]
 - src/lime/utils/Log.cpp  [haxe,release]
 - src/lime/utils/AssetCache.cpp  [haxe,release]
 - src/lime/utils/ObjectPool_openfl_geom_Rectangle.cpp
 - src/lime/utils/ObjectPool_openfl_geom_Matrix.cpp
 - src/gamecontrol/Localworld.cpp
Error: Localworld.cpp
c:\azrafe7\haxegon-samples_git\complete games\02 - tiny heist\bin\windows\obj\src\gamecontrol\localw
orld.cpp(1869) : fatal error C1001: An internal error has occurred in the compiler.
(compiler file 'f:\dd\vctools\compiler\utc\src\p2\main.c', line 255)
 To work around this problem, try simplifying or changing the program near the locations listed abov
e.
Please choose the Technical Support command on the Visual C++
 Help menu, or open the Technical Support help file for more information
  cl!CloseTypeServerPDB()+0x28a30
  cl!CloseTypeServerPDB()+0x28a30

INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe'
    Please choose the Technical Support command on the Visual C++
    Help menu, or open the Technical Support help file for more information
```

While compiling with either of:
 - lime test windows -debug
 - lime test neko
 - lime test neko -debug

works just fine!

I'm on win 8 (64bit) using:
 - haxe 3.4.6
 - openfl 7.1.2
 - lime 6.2.0
 - hxcpp 3.4.188
 - VS 2015

(maybe the starling update might have impacted this? I didn't test it before so I can't tell - yet)

**Comment by TerryCavanagh** [comment]
Ack, weird. Reopening!

**Comment by TerryCavanagh** [comment]
So I guess the cause of this is our different version of Visual Studio. The changes to Starling are pretty minor (I mostly just updated to maintain compatibility), and everything else is basically the same.

(From googling around, the only thing I can suggest which might help is to do a clean build - i.e. delete your bin folder from Tiny Heist. I dunno, worth a shot!)

(As an aside, I'm sorta wondering if I should just remove Tiny Heist as an example. It's not at all useful as an example of how to use Haxegon, since it was salvaged and pieced together at several different points in Haxegon's life. It's kind of a mess. I only included it because it's the only big, full, finished Haxegon game out there right now...)

**Comment by azrafe7** [comment]
From reading around it could be a stackoverflow/infinite-recursion in the compiler trying to optimize some code.

Looking at localworld.cpp(1869) I can see that it points to the drill() function, and indeed inspecting the related loction inside LocalWorld.hx file there is a recursion:
https://github.com/haxegon/haxegon-samples/blob/60a8b9f09eda2792c5f95bd2c1d4b50aa0899d31/complete%20games/02%20-%20Tiny%20Heist/src/gamecontrol/Localworld.hx#L907-L919

You can try rewriting it to be iterative and see if the error goes away.

PS: I'd be ok if the sample got removed (it's not that easy to follow), but as you said that's the only available big project using the lib. Either way I'd like to see if we can successfully fix the error.

**Comment by TerryCavanagh** [comment]
Could well be the culprit! Give it a go now and see if it still breaks! (and thanks for the lead)

**Comment by azrafe7** [comment]
And that was it!! Now successfully compiles and run! :+1: :tada:

**Comment by TerryCavanagh** [comment]
Amazing! Thank you for your help! 👍
